management:
    server:
     port: 9000
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            exposure:
                include: prometheus,health,info,mappings,openapi, swaggerui
            base-path: "/manage"
server:
    port: 8888
springdoc:
  use-management-port: true
  api-docs:
    enabled: true
    path: /api-docs   

spring:
    jackson:
        serialization:
            INDENT_OUTPUT: true
    profiles:
        active: local
    data:
      rest:
        base-path: api
